//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vp_Semester_Project.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_marks
    {
        public int Id { get; set; }
        public string Batch_s { get; set; }
        public int Batch_y { get; set; }
        public int Roll_no { get; set; }
        public string Class_name { get; set; }
        public int Course_id { get; set; }
        public int Quiz_1 { get; set; }
        public int Quiz_2 { get; set; }
        public int Quiz_3 { get; set; }
        public int Quiz_4 { get; set; }
        public int Assignment_1 { get; set; }
        public int Assignment_2 { get; set; }
        public int Assignment_3 { get; set; }
        public int Assignment_4 { get; set; }
        public int Mids { get; set; }
        public int Terinals { get; set; }
    
        public virtual Course_Reg Course_Reg { get; set; }
    }
}
