//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vp_Semester_Project.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Attendance
    {
        public int Id { get; set; }
        public string Batch_s { get; set; }
        public int Batch_y { get; set; }
        public int Roll_no { get; set; }
        public string Class_name { get; set; }
        public int Course_id { get; set; }
        public int attendance_status { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Course_Reg Course_Reg { get; set; }
    }
}
