//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vp_Semester_Project.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Reg
    {
        public int SerialNo { get; set; }
        public string Batch_s { get; set; }
        public int Batch_y { get; set; }
        public int Roll_no { get; set; }
        public string Class_name { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public string Father_name { get; set; }
        public System.DateTime Dob { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Login_password { get; set; }
    }
}
